name: GitHub Pre-Release

on:
  workflow_call:

jobs:
  github-release:
    name: GitHub Pre-Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create GitHub pre-release
        run: |
          gh release create "$GITHUB_REF_NAME" \
            --title "$GITHUB_REF_NAME" \
            --generate-notes \
            --prerelease
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}