name: Sonarcloud Scan
on:
  workflow_call:
    inputs:
      project-name:
        description: 'project name to use in SonarCloud'
        type: string
        default: ''
      src-folder:
        description: 'Project source folder'
        type: string
        default: 'src/'
    secrets:
      sonar-token:
        required: true
      sonar-orga:
        required: true

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v5
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.sonar-token }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=${{ secrets.sonar-orga }}
            -Dsonar.projectKey=${{ inputs.project-name }}
            -Dsonar.sources=${{ inputs.src-folder }}
            -Dsonar.test.exclusions=tests/**
            -Dsonar.tests=tests/
            -Dsonar.verbose=true
